export const key = "PAGES"

export const value = [
	{
		sref: "root.company.dashboard",
		badgeKey: null,
		enabled: true,
		icon: "icon-dashboard",
		name: "Dashboard",
		onlySingleCompanies: false,
		role: ["Admin", "User"],
	},
	{
		sref: "root.company.campaigns",
		badgeKey: null,
		enabled: true,
		icon: "icon-bullhorn",
		name: "Campaigns",
		onlySingleCompanies: false,
		role: ["Admin"],
	},
	{
		sref: "root.company.send",
		badgeKey: null,
		enabled: true,
		icon: "icon-send",
		name: "Send",
		onlySingleCompanies: false,
		role: ["Admin", "User"],
	},
	// {
	// 	sref:"root.company.leaderboards",
	// 	badgeKey:null,
	// 	enabled: true,
	// 	icon: "icon-trophy",
	// 	name: "Leaderboards",
	// 	onlySingleCompanies: false,
	// 	role:["Admin"],
	// },
	{
		sref: null,
		enabled: true,
		icon: "icon-pie-chart",
		name: "Reports",
		pages: [
			{
				sref: "root.company.report.campaign",
				badgeKey: null,
				enabled: true,
				icon: "icon-bullhorn",
				name: "Campaign Report",
				onlySingleCompanies: false,
				role: ["Admin"],
			},
			{
				sref: "root.company.report.user",
				badgeKey: null,
				enabled: true,
				icon: "icon-user",
				name: "User Report",
				onlySingleCompanies: false,
				role: ["Admin", "User"],
			},
			// Uncomment to add the Contact Rports nav item back
			// {
			// 	sref:"root.company.report.contact",
			// 	badgeKey:null,
			// 	enabled: true,
			// 	icon: "icon-users",
			// 	name: "Contact Report",
			// 	onlySingleCompanies: false,
			// 	role:["Admin", "User"],
			// },
			{
				sref: "root.company.report.recipient",
				badgeKey: null,
				enabled: true,
				icon: "icon-user-plus",
				name: "Recipient Report",
				onlySingleCompanies: false,
				role: ["Admin", "User"],
			},
		],
	},
	// {
	// 	sref:"root.company.playlist",
	// 	badgeKey:null,
	// 	enabled: true,
	// 	icon: "icon-play-circle",
	// 	name: "Playlists",
	// 	onlySingleCompanies: false,
	// 	role:["Admin"],
	// },
	{
		sref: "root.company.message",
		badgeKey: "messages",
		enabled: true,
		icon: "icon-envelope",
		name: "Messages",
		onlySingleCompanies: false,
		role: ["Admin", "User"],
	},
	{
		sref: "root.company.contacts",
		badgeKey: null,
		enabled: true,
		icon: "icon-address-book",
		name: "My Contacts",
		onlySingleCompanies: false,
		role: ["Admin", "User"],
	},

	{
		sref: null,
		enabled: true,
		icon: "icon-cog",
		name: "Settings",
		pages: [
			{
				sref: "root.company.settings",
				badgeKey: null,
				enabled: true,
				icon: "icon-paint-brush",
				name: "Branding",
				onlySingleCompanies: false,
				role: ["Admin"],
			},
			{
				sref: "root.company.manage",
				badgeKey: null,
				enabled: true,
				icon: "icon-user-plus",
				name: "Manage Users",
				onlySingleCompanies: false,
				role: ["Admin"],
			},
			{
				sref: "root.company.user-settings",
				badgeKey: null,
				enabled: true,
				icon: "icon-cog",
				name: "User Settings",
				onlySingleCompanies: false,
				role: ["Admin", "User"],
			},
		],
	},
	{
		sref: "root.company-select",
		badgeKey: null,
		enabled: true,
		icon: "icon-exchange",
		name: "Switch Company",
		onlySingleCompanies: true,
		role: ["Admin", "User"],
	},
	{
		sref: "root.company.logout",
		badgeKey: null,
		enabled: true,
		icon: "icon-power-off",
		name: "Log Out",
		onlySingleCompanies: false,
		role: ["Admin", "User", "Contact"],
	},
]
